# Generated by Django 5.2.6 on 2025-10-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_role',
            field=models.CharField(choices=[('SMALLHOLDER_FARMER', 'Smallholder Farmer'), ('COMMERCIAL_FARMER', 'Commercial Farmer'), ('ORGANIC_SPECIALIST', 'Organic Specialist'), ('LIVESTOCK_FARMER', 'Livestock Farmer'), ('INDIVIDUAL_CONSUMER', 'Individual Consumer'), ('RESTAURANT_BUSINESS', 'Restaurant/Business'), ('EXPORT_CLIENT', 'Export Client'), ('INSTITUTIONAL_BUYER', 'Institutional Buyer'), ('LOGISTICS_PROVIDER', 'Logistics Provider'), ('INPUT_SUPPLIER', 'Input Supplier'), ('MACHINERY_PROVIDER', 'Machinery Provider'), ('SERVICE_PROVIDER', 'Service Provider'), ('FINANCIAL_ADVISOR', 'Financial Advisor'), ('TECHNICAL_ADVISOR', 'Technical Advisor'), ('LEGAL_SPECIALIST', 'Legal Specialist'), ('MARKET_ANALYST', 'Market Analyst'), ('PLATFORM_ADMIN', 'Platform Admin'), ('BUSINESS_ADMIN', 'Business Admin')], default='SMALLHOLDER_FARMER', max_length=50),
        ),
    ]
