# Generated by Django 5.2.6 on 2025-10-02 11:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmanalytics',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='farmtask',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='plot',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='farmtask',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farms.plot'),
        ),
        migrations.AddField(
            model_name='crophistory',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_history', to='farms.plot'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='farms_farm_search__e11fc8_gin'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['owner', 'soil_type'], name='farms_farm_owner_i_40b909_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['productivity_score'], name='farms_farm_product_216472_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('farm', 'plot_number')},
        ),
    ]
