# Generated by Django 5.2.6 on 2025-10-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['-created_at']},
        ),
    ]
