# Generated by Django 5.2.6 on 2025-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='ai_prompt_templates',
            field=models.JSONField(blank=True, default=dict, help_text='AI prompt templates for this category'),
        ),
    ]
