# Generated by Django 5.2.6 on 2025-10-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_productcategory_ai_prompt_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred locations'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='search_history',
            field=models.JSONField(blank=True, default=list, help_text="User's search history for personalization", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'REFUNDED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_location',
            field=models.CharField(blank=True, default='', help_text='Primary preferred location', max_length=200),
        ),
    ]
