# Generated by Django 5.2.6 on 2025-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_userpreference_preferred_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquerylog',
            name='filters_applied',
            field=models.JSONField(blank=True, default=dict, help_text='Filters applied during search'),
        ),
    ]
