# Generated by Django 5.2.6 on 2025-10-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['model_type', 'created_at'], name='model_perfo_model_t_45c8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['is_production'], name='model_perfo_is_prod_47a873_idx'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.croprecommendation'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='croprecommendation',
            index=models.Index(fields=['user_profile', 'created_at'], name='crop_recomm_user_pr_03cb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='croprecommendation',
            index=models.Index(fields=['confidence_score'], name='crop_recomm_confide_83ace4_idx'),
        ),
        migrations.AddIndex(
            model_name='croprecommendation',
            index=models.Index(fields=['selected_crop'], name='crop_recomm_selecte_8aa10c_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['recommendation', 'created_at'], name='user_feedba_recomme_05846f_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['yield_rating'], name='user_feedba_yield_r_edc869_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['actual_crop_planted'], name='user_feedba_actual__5901c2_idx'),
        ),
    ]
